package heracles

import (
	"fmt"
	"strings"

	"fecim-lattice-tools/shared/export"
)

// HeraclesNetlistConfig holds parameters for generating an ngspice netlist
// that instantiates a ferroelectric capacitor using the Heracles Verilog-A
// compact model and runs a DC voltage sweep for P-E loop extraction.
type HeraclesNetlistConfig struct {
	// Vmax is the peak sweep voltage in volts (default 3.0).
	Vmax float64

	// Steps is the number of points per half-sweep (default 100).
	Steps int

	// Temperature in Kelvin (default 300).
	Temperature float64

	// Thickness of the ferroelectric film in nanometers (default 10).
	ThicknessNm float64

	// AreaUm2 is the capacitor area in um^2 (default 1.0).
	AreaUm2 float64

	// ModelPath is the filesystem path to the Heracles Verilog-A file.
	ModelPath string

	// OutputFile is the path where ngspice will write simulation results.
	OutputFile string
}

// DefaultHeraclesNetlistConfig returns a configuration matching the
// Reference10nmHfO2_300K dataset: 10 nm HfO2 at 300 K swept to +/-3 V.
func DefaultHeraclesNetlistConfig() HeraclesNetlistConfig {
	return HeraclesNetlistConfig{
		Vmax:        3.0,
		Steps:       100,
		Temperature: 300,
		ThicknessNm: 10,
		AreaUm2:     1.0,
		ModelPath:   "opensource/heracles/heracles.va",
		OutputFile:  "heracles_pe.csv",
	}
}

// GenerateHeraclesFECapNetlist produces an ngspice deck that:
//  1. Includes the Heracles Verilog-A compact model
//  2. Instantiates a ferroelectric capacitor between nodes top and gnd
//  3. Sweeps a DC voltage source from -Vmax to +Vmax and back
//  4. Exports V(top) and I(Vsrc) to a CSV file for post-processing
//
// The returned string is a complete ngspice input deck ready to be written
// to a .sp file and executed with `ngspice -b`.
func GenerateHeraclesFECapNetlist(config HeraclesNetlistConfig) string {
	if config.Vmax <= 0 {
		config.Vmax = 3.0
	}
	if config.Steps <= 0 {
		config.Steps = 100
	}
	if config.Temperature <= 0 {
		config.Temperature = 300
	}
	if config.ThicknessNm <= 0 {
		config.ThicknessNm = 10
	}
	if config.AreaUm2 <= 0 {
		config.AreaUm2 = 1.0
	}
	if config.ModelPath == "" {
		config.ModelPath = "opensource/heracles/heracles.va"
	}
	if config.OutputFile == "" {
		config.OutputFile = "heracles_pe.csv"
	}

	// Step voltage for the piecewise-linear sweep.
	stepV := config.Vmax / float64(config.Steps)
	// Time per step — a nominal period for the transient source.
	// We use 1 ns steps giving enough settling time for a compact model.
	stepTimeNs := 1.0
	totalSteps := 4 * config.Steps // -Vmax -> +Vmax -> -Vmax (full loop)

	var b strings.Builder

	// Simulation disclaimer header
	b.WriteString(export.SPICEDisclaimer())

	// Title line
	fmt.Fprintf(&b, "* Heracles FeCap P-E Loop Extraction\n")
	fmt.Fprintf(&b, "* Generated by fecim-lattice-tools heracles validation\n")
	fmt.Fprintf(&b, "* Temperature: %.1f K, Thickness: %.1f nm, Area: %.2f um^2\n", config.Temperature, config.ThicknessNm, config.AreaUm2)
	fmt.Fprintf(&b, "\n")

	// Include the Verilog-A model
	fmt.Fprintf(&b, ".include \"%s\"\n", config.ModelPath)
	fmt.Fprintf(&b, "\n")

	// Temperature setting
	fmt.Fprintf(&b, ".param temp_val=%.1f\n", config.Temperature)
	fmt.Fprintf(&b, ".param thickness_nm=%.1f\n", config.ThicknessNm)
	fmt.Fprintf(&b, ".param area_um2=%.2f\n", config.AreaUm2)
	fmt.Fprintf(&b, "\n")

	// Circuit: voltage source driving a Heracles FeCap instance
	// Vsrc between node "top" and ground, measuring current through cap
	fmt.Fprintf(&b, "* Voltage source for sweep\n")
	fmt.Fprintf(&b, "Vsrc top 0 DC 0\n")
	fmt.Fprintf(&b, "\n")

	// Heracles FeCap instance (Verilog-A module)
	// Standard Heracles instantiation: X<name> <top> <bot> heracles_hzo
	fmt.Fprintf(&b, "* Heracles ferroelectric capacitor\n")
	fmt.Fprintf(&b, "Xfecap top 0 heracles_hzo\n")
	fmt.Fprintf(&b, "\n")

	// Model parameters
	fmt.Fprintf(&b, ".model heracles_hzo nmos level=1\n")
	fmt.Fprintf(&b, "\n")

	// Control block: DC sweep and data export
	fmt.Fprintf(&b, ".control\n")
	fmt.Fprintf(&b, "  set temp=$&temp_val\n")
	fmt.Fprintf(&b, "\n")

	// Ascending sweep: -Vmax to +Vmax
	fmt.Fprintf(&b, "  * Ascending branch: -Vmax to +Vmax\n")
	fmt.Fprintf(&b, "  dc Vsrc %.4f %.4f %.6f\n", -config.Vmax, config.Vmax, stepV)
	fmt.Fprintf(&b, "  let asc_v = v(top)\n")
	fmt.Fprintf(&b, "  let asc_i = Vsrc#branch\n")
	fmt.Fprintf(&b, "\n")

	// Descending sweep: +Vmax to -Vmax
	fmt.Fprintf(&b, "  * Descending branch: +Vmax to -Vmax\n")
	fmt.Fprintf(&b, "  dc Vsrc %.4f %.4f %.6f\n", config.Vmax, -config.Vmax, -stepV)
	fmt.Fprintf(&b, "  let desc_v = v(top)\n")
	fmt.Fprintf(&b, "  let desc_i = Vsrc#branch\n")
	fmt.Fprintf(&b, "\n")

	// Write results to output file
	fmt.Fprintf(&b, "  * Export data\n")
	fmt.Fprintf(&b, "  write %s asc_v asc_i desc_v desc_i\n", config.OutputFile)
	fmt.Fprintf(&b, "  print asc_v asc_i desc_v desc_i > %s\n", config.OutputFile)
	fmt.Fprintf(&b, ".endc\n")
	fmt.Fprintf(&b, "\n")

	_ = totalSteps
	_ = stepTimeNs

	fmt.Fprintf(&b, ".end\n")

	return b.String()
}
