// pkg/export/spice.go
package export

import (
	"fmt"
	"os"
	"strings"

	"demo6-eda/pkg/compiler"
)

// GenerateSPICE creates ngspice-compatible netlist
func GenerateSPICE(mapping *compiler.CrossbarMapping, vdd float64) string {
	var sb strings.Builder

	sb.WriteString("* FeCIM Crossbar SPICE Netlist\n")
	sb.WriteString("* Generated by Demo 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("* Array: %d cells\n\n", len(mapping.Cells)))

	// Power supply
	sb.WriteString(fmt.Sprintf(".param VDD = %.2f\n", vdd))
	sb.WriteString("VDD vdd 0 DC {VDD}\n\n")

	// Find array dimensions
	maxRow, maxCol := 0, 0
	for _, cell := range mapping.Cells {
		if cell.Row > maxRow {
			maxRow = cell.Row
		}
		if cell.Col > maxCol {
			maxCol = cell.Col
		}
	}

	// Word line drivers (inputs)
	sb.WriteString("* Word Line Drivers\n")
	for row := 0; row <= maxRow; row++ {
		sb.WriteString(fmt.Sprintf("VWL%d wl%d 0 DC 0\n", row, row))
	}
	sb.WriteString("\n")

	// Bit line loads
	sb.WriteString("* Bit Line Loads (1k for sensing)\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("RBL%d bl%d 0 1k\n", col, col))
	}
	sb.WriteString("\n")

	// FeFET cells as resistors (simplified model)
	sb.WriteString("* FeFET Cells (resistor model: R = 1/G)\n")
	for _, cell := range mapping.Cells {
		resistance := 1e6 / cell.Conductance // Ω from μS
		sb.WriteString(fmt.Sprintf("R_%d_%d wl%d bl%d %.2f\n",
			cell.Row, cell.Col, cell.Row, cell.Col, resistance))
	}
	sb.WriteString("\n")

	// Analysis
	sb.WriteString("* Analysis\n")
	sb.WriteString(".op\n")
	sb.WriteString(".control\n")
	sb.WriteString("run\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("print i(RBL%d)\n", col))
	}
	sb.WriteString(".endc\n")
	sb.WriteString(".end\n")

	return sb.String()
}

// ExportSPICE writes netlist to file
func ExportSPICE(mapping *compiler.CrossbarMapping, path string, vdd float64) error {
	content := GenerateSPICE(mapping, vdd)
	return os.WriteFile(path, []byte(content), 0644)
}
