#!/usr/bin/env bash
# FeCIM Netgen LVS Script
# Generated: 2026-02-20
# Cell: fecim_bitcell (architecture: passive, technology: sky130)
#
# Compares schematic SPICE netlist (from circuit design) against
# extracted layout netlist (from Magic extraction or OpenROAD).
#
# Prerequisites:
#   - netgen installed (apt: netgen-lvs, or build from source)
#   - Schematic SPICE: cells/fecim_bitcell/fecim_bitcell.spice  (generated by module6 export)
#   - Layout SPICE:    cells/fecim_bitcell/fecim_bitcell_ext.spice (from Magic .ext → .spice)
#   - PDK setup TCL:   ${PDK_ROOT}/sky130A/libs.tech/netgen/sky130A_setup.tcl
#
# Usage:
#   bash run_lvs.sh
#
# Or run netgen directly:
#   netgen -batch lvs "{cells/fecim_bitcell/fecim_bitcell.spice} {fecim_bitcell}" \
#       "{cells/fecim_bitcell/fecim_bitcell_ext.spice} {fecim_bitcell}" \
#       ${PDK_ROOT}/sky130A/libs.tech/netgen/sky130A_setup.tcl lvs_report.txt -json
#
# LVS PASS means layout matches schematic — safe to tapeout.
# LVS FAIL means connectivity mismatch — must be fixed before tapeout.

set -e

CELL="fecim_bitcell"
SCHEMATIC="cells/${CELL}/${CELL}.spice"
LAYOUT="cells/${CELL}/${CELL}_ext.spice"
SETUP_TCL="${PDK_ROOT}/sky130A/libs.tech/netgen/sky130A_setup.tcl"
REPORT="output/lvs_report.txt"
JSON_REPORT="output/lvs_report.json"

echo "=== FeCIM Netgen LVS ==="
echo "Cell:       ${CELL}"
echo "Schematic:  ${SCHEMATIC}"
echo "Layout:     ${LAYOUT}"
echo "Setup TCL:  ${SETUP_TCL}"
echo ""

# Verify inputs exist
if [[ ! -f "${SCHEMATIC}" ]]; then
    echo "ERROR: Schematic not found: ${SCHEMATIC}"
    echo "  Generate with: fecim-lattice-tools eda cli --spice"
    exit 1
fi
if [[ ! -f "${LAYOUT}" ]]; then
    echo "WARNING: Layout SPICE not found: ${LAYOUT}"
    echo "  Extract from Magic: magic -T ${SETUP_TCL} -rcfile magicrc"
    echo "  Then: extract all; ext2spice -r ${CELL}; ext2spice"
    echo "  Skipping LVS (layout extraction required for real LVS)."
    exit 0
fi
if [[ ! -f "${SETUP_TCL}" ]]; then
    echo "WARNING: PDK setup TCL not found: ${SETUP_TCL}"
    echo "  Using netgen without PDK device definitions."
    SETUP_TCL=""
fi

# Create output directory
mkdir -p output

# Run LVS
echo "Running netgen LVS..."
if [[ -n "${SETUP_TCL}" ]]; then
    netgen -batch lvs \
        "${SCHEMATIC} {${CELL}}" \
        "${LAYOUT} {${CELL}}" \
        "${SETUP_TCL}" \
        "${REPORT}" \
        -json 2>&1 | tee output/lvs_netgen.log
else
    netgen -batch lvs \
        "${SCHEMATIC} {${CELL}}" \
        "${LAYOUT} {${CELL}}" \
        "${REPORT}" \
        -json 2>&1 | tee output/lvs_netgen.log
fi

# Check result
if grep -q "Cells match uniquely" "${REPORT}" 2>/dev/null; then
    echo ""
    echo "✓ LVS PASSED: Layout matches schematic"
    echo "  Report: ${REPORT}"
elif grep -q "NET MISMATCH\|DEVICE MISMATCH\|Errors" "${REPORT}" 2>/dev/null; then
    echo ""
    echo "✗ LVS FAILED: Layout does not match schematic"
    echo "  Check report: ${REPORT}"
    exit 1
else
    echo ""
    echo "⚠ LVS result unclear — check: ${REPORT}"
fi
