// pkg/export/def.go
// DEF (Design Exchange Format) placement generator for FeCIM crossbar arrays
// Supports passive, 1T1R, and 2T1R architectures

package export

import (
	"fmt"
	"os"
	"strings"
	"time"

	"fecim-lattice-tools/module6-eda/pkg/compiler"
	"fecim-lattice-tools/shared/logging"
)

var logDEF = logging.NewLogger("eda-export-def")

// DEFConfig holds configuration for DEF generation
type DEFConfig struct {
	DesignName   string  // Design name (default: fecim_crossbar)
	CellName     string  // Cell master name (default: fecim_bit)
	CellWidth    float64 // Cell width in microns (default from CompileConfig.CellPitch)
	CellHeight   float64 // Cell height in microns (default from CompileConfig.RowHeight)
	OriginX      float64 // Array origin X in microns (default: 10.0)
	OriginY      float64 // Array origin Y in microns (default: 10.0)
	MarginX      float64 // Die margin X in microns (default: 20.0)
	MarginY      float64 // Die margin Y in microns (default: 20.0)
	DatabaseUnit int     // Database units per micron (default: 1000)
}

// DefaultDEFConfig returns standard DEF generation parameters for SKY130
func DefaultDEFConfig() DEFConfig {
	return DEFConfig{
		DesignName:   "fecim_crossbar",
		CellName:     "fecim_bit",
		CellWidth:    0.46, // SKY130 compatible: 2 * 0.23um site width
		CellHeight:   2.72, // SKY130 standard cell row height
		OriginX:      10.0, // 10um from left edge
		OriginY:      10.0, // 10um from bottom edge
		MarginX:      20.0, // 20um margin on each side
		MarginY:      20.0, // 20um margin on top/bottom
		DatabaseUnit: 1000, // DEF standard: 1000 units = 1 micron
	}
}

// DEFConfigFrom creates DEFConfig from ArrayDesign's ArrayConfig.
// Works with all operation modes (Storage, Memory, Compute).
func DEFConfigFrom(design *compiler.ArrayDesign) DEFConfig {
	cfg := DefaultDEFConfig()

	// Use cell dimensions from ArrayConfig if available
	if design.Config.CellPitch > 0 {
		cfg.CellWidth = design.Config.CellPitch
	}
	if design.Config.RowHeight > 0 {
		cfg.CellHeight = design.Config.RowHeight
	}

	// Use design name if provided
	if design.Config.Name != "" {
		cfg.DesignName = design.Config.Name
	}

	// Use architecture-specific cell name
	if design.Config.Architecture == compiler.Arch1T1R {
		cfg.CellName = "fecim_1t1r"
	}
	if design.Config.Architecture == compiler.Arch2T1R {
		cfg.CellName = "fecim_2t1r"
	}

	return cfg
}

// GenerateDEF creates DEF placement file from ArrayDesign.
// Works with all operation modes (Storage, Memory, Compute).
// Architecture is determined from design.Config.Architecture:
//   - "passive": WL[], BL[] pins
//   - "1T1R": WL[], BL[], SL[] pins
func GenerateDEF(design *compiler.ArrayDesign, config DEFConfig) string {
	logDEF.Input("GenerateDEF", map[string]interface{}{
		"designName": config.DesignName, "mode": design.Config.Mode, "arch": design.Config.Architecture,
	})

	var sb strings.Builder

	// Filter cells to export
	cellsToExport := filterActiveCells(design)

	// Find array dimensions from cells to export
	maxRow, maxCol := findCellDimensions(cellsToExport)
	numRows := maxRow + 1
	numCols := maxCol + 1

	// Determine architecture (normalize to lowercase for case-insensitive comparison)
	arch := strings.ToLower(design.Config.Architecture)
	if arch == "" {
		arch = compiler.ArchPassive
	}
	is1T1R := arch == compiler.Arch1T1R
	is2T1R := arch == compiler.Arch2T1R

	// Determine cell name
	cellName := config.CellName
	if is1T1R && cellName == "fecim_bit" {
		cellName = "fecim_1t1r"
	}
	if is2T1R && cellName == "fecim_bit" {
		cellName = "fecim_2t1r"
	}

	// Calculate die area in microns
	arrayWidth := float64(numCols) * config.CellWidth
	arrayHeight := float64(numRows) * config.CellHeight
	dieWidth := arrayWidth + config.OriginX + config.MarginX
	dieHeight := arrayHeight + config.OriginY + config.MarginY

	// Convert to database units
	dbu := config.DatabaseUnit
	dieWidthDBU := int(dieWidth * float64(dbu))
	dieHeightDBU := int(dieHeight * float64(dbu))

	// Header
	sb.WriteString("# FeCIM Array DEF Placement File\n")
	sb.WriteString("# Generated by Module 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("# Operation Mode: %s\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("# Array Size: %d rows x %d cols (%d cells)\n", numRows, numCols, len(cellsToExport)))
	sb.WriteString(fmt.Sprintf("# Architecture: %s\n", arch))
	sb.WriteString(fmt.Sprintf("# Technology: %s\n", design.Config.Technology))
	if is1T1R {
		sb.WriteString("# Note: 1T1R includes Source Line (SL) pins for sneak path mitigation\n")
	}
	if is2T1R {
		sb.WriteString("# Note: 2T1R includes Column Select Line (CSL) pins for individual cell addressing\n")
		sb.WriteString("# CSL pins located at top edge (column transistor gates, same X as BL)\n")
	}
	sb.WriteString("\n")

	// DEF version and design name
	sb.WriteString("VERSION 5.8 ;\n")
	sb.WriteString(fmt.Sprintf("DESIGN %s ;\n", config.DesignName))
	sb.WriteString(fmt.Sprintf("UNITS DISTANCE MICRONS %d ;\n", dbu))
	sb.WriteString("\n")

	// Die area
	sb.WriteString(fmt.Sprintf("DIEAREA ( 0 0 ) ( %d %d ) ;\n", dieWidthDBU, dieHeightDBU))
	sb.WriteString("\n")

	// ROW definitions - required for OpenROAD placement validation
	// Site name must match the SITE defined in the LEF file
	siteName := "fecim_site"
	if is1T1R {
		siteName = "fecim_1t1r_site"
	}
	if is2T1R {
		siteName = "fecim_2t1r_site"
	}
	cellWidthDBU := int(config.CellWidth * float64(dbu))
	cellHeightDBU := int(config.CellHeight * float64(dbu))
	originXDBU := int(config.OriginX * float64(dbu))
	originYDBU := int(config.OriginY * float64(dbu))

	for row := 0; row < numRows; row++ {
		rowY := originYDBU + row*cellHeightDBU
		orient := "N"
		if row%2 == 1 {
			orient = "FS" // Flip alternate rows for power grid alignment
		}
		sb.WriteString(fmt.Sprintf("ROW ROW_%d %s %d %d %s DO %d BY 1 STEP %d 0 ;\n",
			row, siteName, originXDBU, rowY, orient, numCols, cellWidthDBU))
	}
	sb.WriteString("\n")

	// Components section
	sb.WriteString(fmt.Sprintf("COMPONENTS %d ;\n", len(cellsToExport)))

	for _, cell := range cellsToExport {
		// Instance name matches spice.go and verilog.go convention: R_{row}_{col}
		instanceName := fmt.Sprintf("R_%d_%d", cell.Row, cell.Col)

		// Calculate placement coordinates in database units
		// Origin is at bottom-left, cells placed in row-major order
		cellX := config.OriginX + float64(cell.Col)*config.CellWidth
		cellY := config.OriginY + float64(cell.Row)*config.CellHeight
		cellXDBU := int(cellX * float64(dbu))
		cellYDBU := int(cellY * float64(dbu))

		// FIXED placement with N (north) orientation
		sb.WriteString(fmt.Sprintf("    - %s %s + FIXED ( %d %d ) N ;\n",
			instanceName, cellName, cellXDBU, cellYDBU))
	}

	sb.WriteString("END COMPONENTS\n")
	sb.WriteString("\n")

	// Calculate number of pins
	// Passive: WL[] + BL[] + VPWR + VGND
	// 1T1R: WL[] + BL[] + SL[] + VPWR + VGND
	// 2T1R: WL[] + BL[] + SL[] + CSL[] + VPWR + VGND
	numPins := numRows + numCols + 2
	if is1T1R {
		numPins += numCols // Add SL[] pins
	}
	if is2T1R {
		numPins += numCols // Add SL[] pins
		numPins += numCols // Add CSL[] pins
	}
	sb.WriteString(fmt.Sprintf("PINS %d ;\n", numPins))

	// Word Line pins (left edge)
	for row := 0; row < numRows; row++ {
		pinY := config.OriginY + float64(row)*config.CellHeight + config.CellHeight/2
		pinYDBU := int(pinY * float64(dbu))
		sb.WriteString(fmt.Sprintf("    - WL[%d] + NET WL[%d] + DIRECTION INPUT + USE SIGNAL\n", row, row))
		sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( 80 200 ) + FIXED ( 0 %d ) N ;\n", pinYDBU))
	}

	// Bit Line pins (top edge)
	for col := 0; col < numCols; col++ {
		pinX := config.OriginX + float64(col)*config.CellWidth + config.CellWidth/2
		pinXDBU := int(pinX * float64(dbu))
		sb.WriteString(fmt.Sprintf("    - BL[%d] + NET BL[%d] + DIRECTION INOUT + USE SIGNAL\n", col, col))
		sb.WriteString(fmt.Sprintf("      + LAYER met2 ( 0 0 ) ( 80 80 ) + FIXED ( %d %d ) N ;\n", pinXDBU, dieHeightDBU))
	}

	// Source Line pins for 1T1R and 2T1R (bottom edge, below array)
	if is1T1R || is2T1R {
		for col := 0; col < numCols; col++ {
			pinX := config.OriginX + float64(col)*config.CellWidth + config.CellWidth/2
			pinXDBU := int(pinX * float64(dbu))
			sb.WriteString(fmt.Sprintf("    - SL[%d] + NET SL[%d] + DIRECTION INPUT + USE SIGNAL\n", col, col))
			sb.WriteString(fmt.Sprintf("      + LAYER met2 ( 0 0 ) ( 80 80 ) + FIXED ( %d 0 ) N ;\n", pinXDBU))
		}
	}

	// Column Select Line pins for 2T1R (top edge, like BL).
	// CSL[col] is per-column (vertical wire), so its die-level pin uses the
	// column's X centre — not the row-based Y formula the old code mistakenly used.
	// met1 (vs BL's met2) avoids a layer conflict at the top boundary.
	if is2T1R {
		for col := 0; col < numCols; col++ {
			pinX := config.OriginX + float64(col)*config.CellWidth + config.CellWidth/2
			pinXDBU := int(pinX * float64(dbu))
			sb.WriteString(fmt.Sprintf("    - CSL[%d] + NET CSL[%d] + DIRECTION INPUT + USE SIGNAL\n", col, col))
			sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( 80 200 ) + FIXED ( %d %d ) N ;\n", pinXDBU, dieHeightDBU))
		}
	}

	// Power pins (use VPWR/VGND to match LEF)
	sb.WriteString("    - VPWR + NET VPWR + DIRECTION INPUT + USE POWER\n")
	sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( %d 160 ) + FIXED ( 0 %d ) N ;\n",
		dieWidthDBU, dieHeightDBU-160))
	sb.WriteString("    - VGND + NET VGND + DIRECTION INPUT + USE GROUND\n")
	sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( %d 160 ) + FIXED ( 0 0 ) N ;\n", dieWidthDBU))

	sb.WriteString("END PINS\n")
	sb.WriteString("\n")

	// Calculate number of nets
	// Passive: WL nets + BL nets + VPWR + VGND
	// 1T1R: WL nets + BL nets + SL nets + VPWR + VGND
	// 2T1R: WL nets + BL nets + SL nets + CSL nets + VPWR + VGND
	numNets := numRows + numCols + 2
	if is1T1R {
		numNets += numCols
	}
	if is2T1R {
		numNets += numCols // SL nets
		numNets += numCols // CSL nets
	}
	sb.WriteString(fmt.Sprintf("NETS %d ;\n", numNets))

	// Word Line nets
	for row := 0; row < numRows; row++ {
		sb.WriteString(fmt.Sprintf("    - WL[%d]\n", row))
		sb.WriteString(fmt.Sprintf("      ( PIN WL[%d] )", row))
		// Connect all cells in this row
		for _, cell := range cellsToExport {
			if cell.Row == row {
				sb.WriteString(fmt.Sprintf(" ( R_%d_%d WL )", cell.Row, cell.Col))
			}
		}
		sb.WriteString(" ;\n")
	}

	// Bit Line nets
	for col := 0; col < numCols; col++ {
		sb.WriteString(fmt.Sprintf("    - BL[%d]\n", col))
		sb.WriteString(fmt.Sprintf("      ( PIN BL[%d] )", col))
		// Connect all cells in this column
		for _, cell := range cellsToExport {
			if cell.Col == col {
				sb.WriteString(fmt.Sprintf(" ( R_%d_%d BL )", cell.Row, cell.Col))
			}
		}
		sb.WriteString(" ;\n")
	}

	// Source Line nets for 1T1R and 2T1R
	if is1T1R || is2T1R {
		for col := 0; col < numCols; col++ {
			sb.WriteString(fmt.Sprintf("    - SL[%d]\n", col))
			sb.WriteString(fmt.Sprintf("      ( PIN SL[%d] )", col))
			// Connect all cells in this column
			for _, cell := range cellsToExport {
				if cell.Col == col {
					sb.WriteString(fmt.Sprintf(" ( R_%d_%d SL )", cell.Row, cell.Col))
				}
			}
			sb.WriteString(" ;\n")
		}
	}

	// Column Select Line nets for 2T1R
	if is2T1R {
		for col := 0; col < numCols; col++ {
			sb.WriteString(fmt.Sprintf("    - CSL[%d]\n", col))
			sb.WriteString(fmt.Sprintf("      ( PIN CSL[%d] )", col))
			// Connect all cells in this column
			for _, cell := range cellsToExport {
				if cell.Col == col {
					sb.WriteString(fmt.Sprintf(" ( R_%d_%d CSL )", cell.Row, cell.Col))
				}
			}
			sb.WriteString(" ;\n")
		}
	}

	// Power nets (use VPWR/VGND to match LEF)
	sb.WriteString("    - VPWR ( PIN VPWR )")
	for _, cell := range cellsToExport {
		sb.WriteString(fmt.Sprintf(" ( R_%d_%d VPWR )", cell.Row, cell.Col))
	}
	sb.WriteString(" ;\n")

	sb.WriteString("    - VGND ( PIN VGND )")
	for _, cell := range cellsToExport {
		sb.WriteString(fmt.Sprintf(" ( R_%d_%d VGND )", cell.Row, cell.Col))
	}
	sb.WriteString(" ;\n")

	sb.WriteString("END NETS\n")
	sb.WriteString("\n")

	sb.WriteString("END DESIGN\n")

	return sb.String()
}

// GenerateDEFWithDefaults uses default configuration
func GenerateDEFWithDefaults(design *compiler.ArrayDesign) string {
	return GenerateDEF(design, DEFConfigFrom(design))
}

// ExportDEF writes DEF placement file.
// Works with all operation modes (Storage, Memory, Compute).
func ExportDEF(design *compiler.ArrayDesign, path string) error {
	content := GenerateDEFWithDefaults(design)
	return os.WriteFile(path, []byte(content), 0644)
}

// ExportDEFWithConfig writes DEF placement file with custom config
func ExportDEFWithConfig(design *compiler.ArrayDesign, path string, config DEFConfig) error {
	content := GenerateDEF(design, config)
	return os.WriteFile(path, []byte(content), 0644)
}
