// pkg/export/lattice_generator.go
// Standalone FeCIM lattice generator with simple API
// Naming convention: cell_{row}_{col}

package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	maxLatticeDim   = 2048
	maxLatticeCells = 1_000_000
)

func ValidateLatticeDimensions(rows, cols int) error {
	if rows <= 0 || cols <= 0 {
		return fmt.Errorf("rows and cols must be > 0")
	}
	if rows > maxLatticeDim || cols > maxLatticeDim {
		return fmt.Errorf("rows/cols exceed max dimension %d", maxLatticeDim)
	}
	if rows > maxLatticeCells/cols {
		return fmt.Errorf("array too large: %d x %d exceeds %d cells", rows, cols, maxLatticeCells)
	}
	return nil
}

// GenerateLatticeVerilog generates Verilog for a rows x cols FeCIM array
// Uses cell_{row}_{col} naming convention
func GenerateLatticeVerilog(rows, cols int) string {
	if err := ValidateLatticeDimensions(rows, cols); err != nil {
		return fmt.Sprintf("// invalid lattice dimensions: %v\n", err)
	}
	var sb strings.Builder

	// Header
	sb.WriteString("// FeCIM Lattice Verilog Netlist\n")
	sb.WriteString("// Generated by FeCIM Lattice Generator\n")
	sb.WriteString(fmt.Sprintf("// Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("// Array Size: %d x %d (%d cells)\n", rows, cols, rows*cols))
	sb.WriteString("\n")

	// Module declaration
	sb.WriteString(fmt.Sprintf("module lattice_%dx%d (\n", rows, cols))
	sb.WriteString(fmt.Sprintf("    input  wire [%d:0] WL,  // Word Lines\n", rows-1))
	sb.WriteString(fmt.Sprintf("    inout  wire [%d:0] BL,  // Bit Lines\n", cols-1))
	sb.WriteString("    inout  wire       VPWR,\n")
	sb.WriteString("    inout  wire       VGND\n")
	sb.WriteString(");\n\n")

	// Cell instantiations
	sb.WriteString("    // FeCIM cell instances\n")
	for row := 0; row < rows; row++ {
		for col := 0; col < cols; col++ {
			instanceName := fmt.Sprintf("cell_%d_%d", row, col)
			sb.WriteString(fmt.Sprintf("    fecim_bit %s (\n", instanceName))
			sb.WriteString(fmt.Sprintf("        .WL  (WL[%d]),\n", row))
			sb.WriteString(fmt.Sprintf("        .BL  (BL[%d]),\n", col))
			sb.WriteString("        .VPWR (VPWR),\n")
			sb.WriteString("        .VGND (VGND)\n")
			sb.WriteString("    );\n\n")
		}
	}

	sb.WriteString("endmodule\n")
	return sb.String()
}

// GenerateLatticeDEF generates DEF placement for a rows x cols FeCIM array
// Uses cell_{row}_{col} naming convention matching the Verilog
func GenerateLatticeDEF(rows, cols int) string {
	if err := ValidateLatticeDimensions(rows, cols); err != nil {
		return fmt.Sprintf("# invalid lattice dimensions: %v\n", err)
	}
	var sb strings.Builder

	// Cell dimensions in microns
	cellWidth := 0.46
	cellHeight := 2.72
	originX := 10.0
	originY := 10.0
	margin := 20.0
	dbu := 1000 // Database units per micron

	// Calculate die area
	arrayWidth := float64(cols) * cellWidth
	arrayHeight := float64(rows) * cellHeight
	dieWidth := arrayWidth + originX + margin
	dieHeight := arrayHeight + originY + margin
	dieWidthDBU := int(dieWidth * float64(dbu))
	dieHeightDBU := int(dieHeight * float64(dbu))

	// Header
	sb.WriteString("# FeCIM Lattice DEF Placement\n")
	sb.WriteString("# Generated by FeCIM Lattice Generator\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("# Array Size: %d x %d (%d cells)\n", rows, cols, rows*cols))
	sb.WriteString("\n")

	// DEF header
	sb.WriteString("VERSION 5.8 ;\n")
	sb.WriteString(fmt.Sprintf("DESIGN lattice_%dx%d ;\n", rows, cols))
	sb.WriteString(fmt.Sprintf("UNITS DISTANCE MICRONS %d ;\n", dbu))
	sb.WriteString("\n")

	// Die area
	sb.WriteString(fmt.Sprintf("DIEAREA ( 0 0 ) ( %d %d ) ;\n", dieWidthDBU, dieHeightDBU))
	sb.WriteString("\n")

	// Components section
	numCells := rows * cols
	sb.WriteString(fmt.Sprintf("COMPONENTS %d ;\n", numCells))

	for row := 0; row < rows; row++ {
		for col := 0; col < cols; col++ {
			instanceName := fmt.Sprintf("cell_%d_%d", row, col)
			cellX := originX + float64(col)*cellWidth
			cellY := originY + float64(row)*cellHeight
			cellXDBU := int(cellX * float64(dbu))
			cellYDBU := int(cellY * float64(dbu))
			sb.WriteString(fmt.Sprintf("    - %s fecim_bit + FIXED ( %d %d ) N ;\n",
				instanceName, cellXDBU, cellYDBU))
		}
	}
	sb.WriteString("END COMPONENTS\n")
	sb.WriteString("\n")

	// Pins section
	numPins := rows + cols + 2 // WL + BL + VPWR + VGND
	sb.WriteString(fmt.Sprintf("PINS %d ;\n", numPins))

	// Word Line pins (left edge)
	for row := 0; row < rows; row++ {
		pinY := originY + float64(row)*cellHeight + cellHeight/2
		pinYDBU := int(pinY * float64(dbu))
		sb.WriteString(fmt.Sprintf("    - WL[%d] + NET WL[%d] + DIRECTION INPUT + USE SIGNAL\n", row, row))
		sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( 80 200 ) + FIXED ( 0 %d ) N ;\n", pinYDBU))
	}

	// Bit Line pins (top edge)
	for col := 0; col < cols; col++ {
		pinX := originX + float64(col)*cellWidth + cellWidth/2
		pinXDBU := int(pinX * float64(dbu))
		sb.WriteString(fmt.Sprintf("    - BL[%d] + NET BL[%d] + DIRECTION INOUT + USE SIGNAL\n", col, col))
		sb.WriteString(fmt.Sprintf("      + LAYER met2 ( 0 0 ) ( 80 80 ) + FIXED ( %d %d ) N ;\n", pinXDBU, dieHeightDBU))
	}

	// Power pins
	sb.WriteString("    - VPWR + NET VPWR + DIRECTION INPUT + USE POWER\n")
	sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( %d 160 ) + FIXED ( 0 %d ) N ;\n",
		dieWidthDBU, dieHeightDBU-160))
	sb.WriteString("    - VGND + NET VGND + DIRECTION INPUT + USE GROUND\n")
	sb.WriteString(fmt.Sprintf("      + LAYER met1 ( 0 0 ) ( %d 160 ) + FIXED ( 0 0 ) N ;\n", dieWidthDBU))

	sb.WriteString("END PINS\n")
	sb.WriteString("\n")

	// Nets section
	numNets := rows + cols + 2
	sb.WriteString(fmt.Sprintf("NETS %d ;\n", numNets))

	// Word Line nets
	for row := 0; row < rows; row++ {
		sb.WriteString(fmt.Sprintf("    - WL[%d]\n", row))
		sb.WriteString(fmt.Sprintf("      ( PIN WL[%d] )", row))
		for col := 0; col < cols; col++ {
			sb.WriteString(fmt.Sprintf(" ( cell_%d_%d WL )", row, col))
		}
		sb.WriteString(" ;\n")
	}

	// Bit Line nets
	for col := 0; col < cols; col++ {
		sb.WriteString(fmt.Sprintf("    - BL[%d]\n", col))
		sb.WriteString(fmt.Sprintf("      ( PIN BL[%d] )", col))
		for row := 0; row < rows; row++ {
			sb.WriteString(fmt.Sprintf(" ( cell_%d_%d BL )", row, col))
		}
		sb.WriteString(" ;\n")
	}

	// Power nets
	sb.WriteString("    - VPWR ( PIN VPWR )")
	for row := 0; row < rows; row++ {
		for col := 0; col < cols; col++ {
			sb.WriteString(fmt.Sprintf(" ( cell_%d_%d VPWR )", row, col))
		}
	}
	sb.WriteString(" ;\n")

	sb.WriteString("    - VGND ( PIN VGND )")
	for row := 0; row < rows; row++ {
		for col := 0; col < cols; col++ {
			sb.WriteString(fmt.Sprintf(" ( cell_%d_%d VGND )", row, col))
		}
	}
	sb.WriteString(" ;\n")

	sb.WriteString("END NETS\n")
	sb.WriteString("\n")
	sb.WriteString("END DESIGN\n")

	return sb.String()
}

// WriteLatticeVerilog writes Verilog to lattice_{rows}x{cols}.v
func WriteLatticeVerilog(rows, cols int, outputDir string) (string, error) {
	if err := ValidateLatticeDimensions(rows, cols); err != nil {
		return "", err
	}
	filename := filepath.Join(outputDir, fmt.Sprintf("lattice_%dx%d.v", rows, cols))
	content := GenerateLatticeVerilog(rows, cols)
	err := os.WriteFile(filename, []byte(content), 0644)
	return filename, err
}

// WriteLatticeDEF writes DEF to lattice_{rows}x{cols}.def
func WriteLatticeDEF(rows, cols int, outputDir string) (string, error) {
	if err := ValidateLatticeDimensions(rows, cols); err != nil {
		return "", err
	}
	filename := filepath.Join(outputDir, fmt.Sprintf("lattice_%dx%d.def", rows, cols))
	content := GenerateLatticeDEF(rows, cols)
	err := os.WriteFile(filename, []byte(content), 0644)
	return filename, err
}

// GenerateLattice generates both Verilog and DEF files
func GenerateLattice(rows, cols int, outputDir string) error {
	if _, err := WriteLatticeVerilog(rows, cols, outputDir); err != nil {
		return fmt.Errorf("verilog: %w", err)
	}
	if _, err := WriteLatticeDEF(rows, cols, outputDir); err != nil {
		return fmt.Errorf("def: %w", err)
	}
	return nil
}
