// pkg/export/openlane_config.go
// OpenLane v1.x / LibreLane configuration generator for FeCIM crossbar arrays
//
// OpenLane v1 is in maintenance mode (see opensource/OpenLane/README.md).
// For new designs use LibreLane, the Python-based successor:
//   https://librelane.readthedocs.io/
//   pip install librelane
//   python3 -m librelane --config-file config.json
//
// GenerateLibreLaneConfig (scripts.go) produces the extended LibreLane config.
// This function generates the minimal OpenLane v1 compatible JSON config used
// by the Builder & Validation tab.
//
// References:
// [1] OpenLane v1 Configuration:
//
//	https://openlane.readthedocs.io/en/latest/reference/configuration.html
//
// [2] LibreLane (recommended successor):
//
//	https://librelane.readthedocs.io/
//
// [3] FP_DEF_TEMPLATE: Floorplan template for pre-placed macros
// [4] SYNTH_ELABORATE_ONLY: Structural netlist elaboration without logic mapping
// [5] EXTRA_GDS_FILES: Must be generated first via gen_gds.py (see scripts.go)
package export

import (
	"encoding/json"
	"fmt"

	"fecim-lattice-tools/module6-eda/pkg/config"
	"fecim-lattice-tools/shared/logging"
)

var logOpenLane = logging.NewLogger("eda-export-openlane")

// GenerateOpenLaneConfig generates an OpenLane v1.x / LibreLane config.json
// for the FeCIM crossbar array.
//
// Key design decisions captured in this config:
//   - DESIGN_IS_CORE=0: this is a macro embedded in a larger design
//   - RUN_CTS=0: no clock tree (crossbar is clockless)
//   - FP_DEF_TEMPLATE: use our pre-placed DEF (regular array grid)
//   - PL_SKIP_INITIAL_PLACEMENT=1: trust our placement, skip OpenROAD placer
//   - SYNTH_ELABORATE_ONLY=1: structural Verilog, no logic optimization needed
//   - SYNTH_READ_BLACKBOX_LIB=1: FeCIM bitcell is a blackbox, not synthesizable
//   - BASE_SDC_FILE: timing constraints (clockless: trivial 0-ns constraints)
//   - EXTRA_GDS_FILES: generate first via: klayout -z -r gen_gds.py [Ref 5]
//
// References: [Ref 1] [Ref 3] [Ref 4]
func GenerateOpenLaneConfig(cfg config.ArrayConfig) string {
	logOpenLane.Input("GenerateOpenLaneConfig", map[string]interface{}{
		"rows": cfg.Rows, "cols": cfg.Cols, "arch": cfg.Architecture,
	})

	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)

	// Convert to microns for DIE_AREA
	dieWidth := float64(cfg.Cols)*cfg.CellWidth + 2.0   // Add 2μm margin
	dieHeight := float64(cfg.Rows)*cfg.CellHeight + 2.0 // Add 2μm margin

	cellDir := fmt.Sprintf("dir::cells/%s", cellName)

	conf := map[string]interface{}{
		// Design identification
		"DESIGN_NAME":    designName,
		"DESIGN_IS_CORE": 0, // Macro, not full chip core [Ref 1]

		// Verilog sources
		"VERILOG_FILES":          fmt.Sprintf("dir::output/%s.v", designName),
		"VERILOG_FILES_BLACKBOX": fmt.Sprintf("%s/%s.v", cellDir, cellName),

		// SDC timing constraints (clockless: all delays = 0)
		// Generated by GenerateSDC() in sdc.go
		"BASE_SDC_FILE": "dir::constraints.sdc",

		// Clock: crossbar has no clock
		"RUN_CTS": 0, // Skip Clock Tree Synthesis [Ref 1]

		// Floorplanning: use pre-placed array DEF [Ref 3]
		"FP_SIZING":                 "absolute",
		"DIE_AREA":                  fmt.Sprintf("0 0 %.3f %.3f", dieWidth, dieHeight),
		"FP_DEF_TEMPLATE":           fmt.Sprintf("dir::output/%s.def", designName),
		"PL_SKIP_INITIAL_PLACEMENT": 1,   // Trust pre-placed DEF [Ref 1]
		"PL_TARGET_DENSITY":         0.6, // Relaxed density for array macros

		// Custom cell library files
		"EXTRA_LEFS": fmt.Sprintf("%s/%s.lef", cellDir, cellName),
		"EXTRA_LIBS": fmt.Sprintf("%s/%s.lib", cellDir, cellName),
		// GDS must be generated before running the flow: klayout -z -r gen_gds.py
		// See GenerateKLayoutGDSScript() in scripts.go [Ref 5]
		"EXTRA_GDS_FILES": fmt.Sprintf("%s/%s.gds", cellDir, cellName),

		// Synthesis: structural elaboration only (no logic optimization) [Ref 4]
		"SYNTH_ELABORATE_ONLY":  1, // No logic mapping for structural Verilog
		"SYNTH_READ_BLACKBOX_LIB": 1, // FeCIM bitcell is a blackbox primitive
	}

	data, _ := json.MarshalIndent(conf, "", "  ")
	return string(data)
}
