// pkg/export/scripts.go
// Flow script generators for FeCIM EDA toolchain integration
//
// Generates ready-to-run scripts for the open-source RTL-to-GDSII flow:
//   Yosys TCL   — synthesis / hierarchy elaboration
//   OpenROAD TCL — placement check, timing report
//   KLayout Py  — DEF + LEF → GDS II stream-out
//   SDC         — generated by sdc.go; referenced here
//   Shell runner — glues steps together for OpenLane v1 / LibreLane
//
// Tool versions targeted (based on local clones under opensource/):
//   OpenLane  v1.x  (TCL-based flow.tcl, maintenance-only; successor is LibreLane)
//   LibreLane latest (Python-based, JSON config compatible with OpenLane v1 format)
//   OpenROAD  latest (Python + TCL bindings)
//   Yosys     latest (pyosys Python API + TCL scripting)
//   KLayout   latest (pya Python API for GDS stream-out)
//
// References:
//   OpenLane  – https://github.com/The-OpenROAD-Project/OpenLane
//   LibreLane – https://github.com/librelane/librelane
//   OpenROAD  – https://openroad.readthedocs.io/
//   Yosys     – https://yosyshq.readthedocs.io/
//   KLayout   – https://www.klayout.de/doc/code/
package export

import (
	"fmt"
	"strings"
	"time"

	"fecim-lattice-tools/module6-eda/pkg/config"
)

// GenerateSynthesisScript returns a Yosys TCL script that:
//  1. Registers the FeCIM bitcell as a blackbox (no internal logic to synthesize)
//  2. Reads the structural array netlist
//  3. Runs hierarchy checking (appropriate for pre-placed structural Verilog)
//
// For designs that include digital control logic (FSM, address decoder, etc.),
// the script includes a commented-out synth_sky130 section that can be activated.
func GenerateSynthesisScript(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)
	tech := strings.ToLower(cfg.Technology)
	if tech == "" {
		tech = "sky130"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`# FeCIM Yosys Synthesis Script
# Generated: %s
# Array: %dx%d, Architecture: %s, Technology: %s
#
# Usage (native):
#   yosys synth.tcl
#
# Usage (Docker/LibreLane):
#   docker run --rm -v $PWD:/design -w /design \
#     ghcr.io/the-openroad-project/openlane:latest yosys synth.tcl
#
# What this script does:
#   Step 1 — Blackbox the FeCIM bitcell (no logic mapping needed for analog cells)
#   Step 2 — Read structural array netlist
#   Step 3 — Hierarchy + DRC check (validates connectivity)
#   Step 4 — Optional: synthesize any attached control logic with synth_%s
#
# Note: SYNTH_ELABORATE_ONLY=1 is set in config.json because the array is
# pre-placed structural Verilog. Only run synth_sky130 if you add a digital
# control wrapper module around the array.

# ── Step 1: Blackbox bitcell ─────────────────────────────────────────────────
# read_verilog -lib: registers cell interface without synthesizing internals
read_verilog -lib cells/%s/%s.v

# ── Step 2: Read structural array netlist ────────────────────────────────────
read_verilog output/%s.v

# ── Step 3: Hierarchy check ──────────────────────────────────────────────────
# -check: assert all modules are defined
# -top: specify top-level module
hierarchy -check -top fecim_crossbar

# Run DRC check on loaded design
check

# Print cell statistics
stat

# ── Step 4 (Optional): Synthesize control logic ──────────────────────────────
# Uncomment the block below ONLY if you have added a digital control wrapper.
# The pure FeCIM array is structural Verilog and does not need logic synthesis.
#
# # Map to %s standard cells:
# synth_%s -top control_wrapper -json output/control_wrapper.json
#
# # Alternative: write structural netlist without optimization:
# # write_verilog -noattr output/%s_synth.v
`, time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture, cfg.Technology,
		tech,
		cellName, cellName,
		designName,
		cfg.Technology, tech, designName))

	return sb.String()
}

// GenerateKLayoutGDSScript returns a KLayout Python script that converts
// the FeCIM DEF + LEF abstract view to a GDS II layout file.
//
// This fills the EXTRA_GDS_FILES slot in config.json which OpenLane/LibreLane
// requires for custom cell stream-out during GDSII merge.
//
// The script uses the pya (KLayout Python API) module which is available
// both in native KLayout and in the OpenLane Docker container.
//
// Usage:
//
//	klayout -z -r gen_gds.py \
//	  -rd lef_file=cells/fecim_bitcell/fecim_bitcell.lef \
//	  -rd def_file=output/fecim_crossbar_NxM.def \
//	  -rd out_file=cells/fecim_bitcell/fecim_bitcell.gds
func GenerateKLayoutGDSScript(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)

	return fmt.Sprintf(`#!/usr/bin/env python3
# FeCIM KLayout DEF+LEF → GDS II Script
# Generated: %s
# Array: %dx%d, Architecture: %s
#
# This script converts the abstract FeCIM bitcell LEF + DEF placement into
# a GDS II layout file for use with OpenLane/LibreLane stream-out.
#
# The output GDS is a simplified rectangular representation suitable for:
#   - OpenLane EXTRA_GDS_FILES injection
#   - KLayout XOR verification (design intent vs. routed GDS)
#   - Educational layout visualization
#
# NOTE: This produces an abstract/educational GDS. Production tapeout requires
#       full transistor-level layout and foundry DRC sign-off (Magic + sky130A PDK).
#
# Usage:
#   klayout -z -r gen_gds.py \
#     -rd lef_file=cells/%s/%s.lef \
#     -rd def_file=output/%s.def \
#     -rd out_file=cells/%s/%s.gds
#
#   Or with Docker (OpenLane image contains klayout + pya):
#   docker run --rm -v $PWD:/design -w /design \
#     ghcr.io/the-openroad-project/openlane:latest \
#     klayout -z -r gen_gds.py \
#       -rd lef_file=cells/%s/%s.lef \
#       -rd def_file=output/%s.def \
#       -rd out_file=cells/%s/%s.gds

import os
import sys

# ── pya import ────────────────────────────────────────────────────────────────
# pya is the KLayout Python API. Available in:
#   - Native KLayout (https://www.klayout.de/build.html)
#   - OpenLane/LibreLane Docker image (bundled klayout)
#
# NOTE: "pip install klayout" installs KLayout's Python module, but the PyPI
# package has LIMITED DEF/LEF support. For reliable DEF→GDS conversion,
# use native KLayout (installed via package manager or downloaded from klayout.de)
# or the OpenLane Docker container.
try:
    import pya
except ImportError:
    print("ERROR: pya not found. Run this script inside KLayout:")
    print("  klayout -z -r gen_gds.py -rd lef_file=... -rd def_file=... -rd out_file=...")
    print("  NOTE: 'pip install klayout' has limited DEF/LEF support.")
    print("  Use native KLayout: https://www.klayout.de/build.html")
    sys.exit(1)

# ── Variable injection (from -rd flags) ───────────────────────────────────────
# KLayout passes -rd NAME=VALUE as module-level variables.
# Default values are provided for standalone testing.
_lef_file = getattr(pya, 'lef_file', None) or lef_file if 'lef_file' in dir() else "cells/%s/%s.lef"
_def_file = getattr(pya, 'def_file', None) or def_file if 'def_file' in dir() else "output/%s.def"
_out_file = getattr(pya, 'out_file', None) or out_file if 'out_file' in dir() else "cells/%s/%s.gds"

print(f"KLayout GDS generator")
print(f"  LEF: {_lef_file}")
print(f"  DEF: {_def_file}")
print(f"  GDS: {_out_file}")

# ── Load layout ───────────────────────────────────────────────────────────────
layout = pya.Layout()

# Use lefdef_config approach: register LEF files as configuration for DEF reading.
# This is the correct KLayout pya API for combined LEF+DEF workflows — it lets
# KLayout resolve cell references in the DEF against the LEF geometry.
layout_options = pya.LoadLayoutOptions()

if os.path.exists(_lef_file):
    # Register LEF as cell-definition source for the DEF reader
    layout_options.lefdef_config.lef_files = [_lef_file]
    print(f"  LEF registered: {_lef_file}")
else:
    print(f"WARNING: LEF file not found: {_lef_file}")
    print("  Generating minimal GDS from DEF placement only")

# Load DEF (defines array placement); LEF geometry is resolved via lefdef_config
if os.path.exists(_def_file):
    layout.read(_def_file, layout_options)
    print(f"  Loaded DEF: {_def_file}")
else:
    print(f"ERROR: DEF file not found: {_def_file}")
    print(f"  Generate DEF first: fecim-lattice-tools eda cli --def")
    sys.exit(1)

# ── Stream out GDS ────────────────────────────────────────────────────────────
os.makedirs(os.path.dirname(os.path.abspath(_out_file)), exist_ok=True)

writer_opts = pya.SaveLayoutOptions()
writer_opts.format = "GDS2"

layout.write(_out_file, writer_opts)
print(f"  Written GDS: {_out_file}")
print()
print("GDS generation complete.")
print("Next steps:")
print("  1. Verify with: klayout " + _out_file)
print("  2. Reference in config.json EXTRA_GDS_FILES field")
print("  3. Run OpenLane/LibreLane flow: ./run_flow.sh")
`,
		time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture,
		cellName, cellName, designName,
		cellName, cellName,
		cellName, cellName, designName,
		cellName, cellName,
		cellName, cellName,
		designName,
		cellName, cellName)
}

// GenerateOpenROADFlowScript returns an OpenROAD TCL script for:
//  1. Reading the FeCIM cell LEF and pre-placed DEF
//  2. Running placement DRC (check_placement)
//  3. Reporting timing (minimal, since design is clockless)
//  4. Exporting results
//
// This script is used by the openlane runner (runner.go RunOpenROAD) and can
// also be run standalone via: openroad -no_splash -exit openroad_flow.tcl
func GenerateOpenROADFlowScript(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)
	dieW := float64(cfg.Cols)*cfg.CellWidth + 2.0
	dieH := float64(cfg.Rows)*cfg.CellHeight + 2.0

	return fmt.Sprintf(`# FeCIM OpenROAD Flow Script
# Generated: %s
# Array: %dx%d, Architecture: %s
# Die area: %.3f x %.3f µm
#
# Usage (native):
#   openroad -no_splash -exit openroad_flow.tcl
#
# Usage (Docker):
#   docker run --rm -v $PWD:/design -w /design \
#     ghcr.io/the-openroad-project/openlane:latest \
#     openroad -no_splash -exit /design/openroad_flow.tcl
#
# Environment variables (set via -rd or export before running):
#   CELL_LEF  — path to FeCIM bitcell LEF (default: cells/%s/%s.lef)
#   DEF_FILE  — path to pre-placed DEF (default: output/%s.def)
#
# What this script does:
#   1. Read custom FeCIM cell LEF (no PDK needed for array-only check)
#   2. Load pre-placed array DEF
#   3. Validate placement (no overlaps, cells within die bounds)
#   4. Report timing (clockless design — expect no setup violations)
#   5. Export OpenROAD database and reports

# ── Configuration ─────────────────────────────────────────────────────────────
set cell_lef  [expr {[info exists ::env(CELL_LEF)] ? $::env(CELL_LEF) : "cells/%s/%s.lef"}]
set def_file  [expr {[info exists ::env(DEF_FILE)]  ? $::env(DEF_FILE)  : "output/%s.def"}]
set out_dir   [expr {[info exists ::env(OUT_DIR)]   ? $::env(OUT_DIR)   : "output/openroad"}]

puts "OpenROAD FeCIM Flow"
puts "  Cell LEF: $cell_lef"
puts "  DEF file: $def_file"
puts "  Output:   $out_dir"

# ── Load technology and design ────────────────────────────────────────────────
# read_lef: register cell geometry (no standard cell PDK needed for array check)
read_lef $cell_lef

# read_def: load pre-placed array (FIXED placement from DEF generator)
read_def $def_file

# ── Placement validation ──────────────────────────────────────────────────────
# check_placement verifies:
#   - No cell-to-cell overlaps
#   - All cells within die bounds
#   - FIXED cells not moved
puts ""
puts "=== Placement Check ==="
if {[catch {check_placement -verbose} err]} {
    puts "WARNING: Placement check reported issues: $err"
} else {
    puts "Placement check passed."
}

# ── Timing report ─────────────────────────────────────────────────────────────
# The FeCIM crossbar has no clock (static write, capacitive read).
# RUN_CTS=0 in config.json skips clock tree synthesis.
# report_checks will show no timing paths (expected for clockless designs).
puts ""
puts "=== Timing Report (clockless design) ==="
if {[catch {report_checks -path_delay max -fields {slew cap input nets fanout} -format full_clock_expanded} err]} {
    puts "INFO: No timing paths found (expected for clockless FeCIM array)"
}

# ── Congestion / area reports ─────────────────────────────────────────────────
puts ""
puts "=== Design Statistics ==="
if {[catch {report_design_area} err]} {
    puts "INFO: report_design_area not available: $err"
}

puts ""
puts "=== Cell Count ==="
if {[catch {report_cell_usage} err]} {
    puts "INFO: report_cell_usage not available: $err"
}

# ── Write output ──────────────────────────────────────────────────────────────
if {[catch {
    file mkdir $out_dir
    write_def $out_dir/%s_placed.def
    puts ""
    puts "Written: $out_dir/%s_placed.def"
} err]} {
    puts "WARNING: write_def failed: $err"
}

puts ""
puts "OpenROAD flow complete for %s"
puts "Die area: %.3f x %.3f µm"
puts "Array:    %dx%d cells (%s architecture)"
`,
		time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture,
		dieW, dieH,
		cellName, cellName, designName,
		cellName, cellName, designName,
		designName, designName,
		designName,
		dieW, dieH,
		cfg.Rows, cfg.Cols, cfg.Architecture)
}

// GenerateFlowRunner returns a shell script that orchestrates the full
// RTL-to-GDS flow using either OpenLane v1 (TCL) or LibreLane (Python).
//
// The script is self-contained: it detects available tools, generates GDS
// via KLayout, and runs OpenLane/LibreLane if installed.
func GenerateFlowRunner(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)

	return fmt.Sprintf(`#!/usr/bin/env bash
# FeCIM RTL-to-GDS Flow Runner
# Generated: %s
# Array: %dx%d, Architecture: %s
#
# This script orchestrates the complete open-source RTL-to-GDS flow:
#   Step 1 — Validate Verilog with Yosys
#   Step 2 — Generate GDS stub with KLayout (DEF+LEF → GDS II)
#   Step 3 — Check placement with OpenROAD
#   Step 4 — Run LibreLane/OpenLane flow (if installed)
#
# Tools used (install via package manager or Docker):
#   yosys    — RTL synthesis (apt: yosys)
#   klayout  — Layout and GDS generation (apt: klayout)
#   openroad — Place & Route (apt: openroad OR via Docker)
#   librelane — RTL-to-GDS flow (pip: librelane, successor to OpenLane)
#   OpenLane  — Legacy RTL-to-GDS flow (Docker: efabless/openlane2)
#
# LibreLane (recommended for new designs):
#   pip install librelane
#   python -m librelane --config-file config.json
#
# OpenLane v1 (legacy, maintenance mode):
#   cd $OPENLANE_ROOT && ./flow.tcl -design fecim_array
#
# Docker alternative (includes all tools):
#   docker pull ghcr.io/the-openroad-project/openlane:latest

set -e
DESIGN="%s"
CELL="%s"
OUTPUT="output"
CELLS_DIR="cells/${CELL}"

echo "==================================================="
echo "FeCIM RTL-to-GDS Flow: ${DESIGN}"
echo "==================================================="
echo ""

# ── Step 1: Yosys hierarchy check ────────────────────────────────────────────
echo "Step 1: Yosys hierarchy check..."
if command -v yosys &>/dev/null; then
    yosys -p "read_verilog -lib ${CELLS_DIR}/${CELL}.v; read_verilog ${OUTPUT}/${DESIGN}.v; hierarchy -check -top fecim_crossbar; check; stat" \
        2>&1 | tee output/yosys_check.log
    echo "  ✓ Yosys check passed — see output/yosys_check.log"
else
    echo "  ⚠ Yosys not found. Skipping synthesis check."
    echo "    Install: sudo apt install yosys"
    echo "    Or run inside Docker image."
fi
echo ""

# ── Step 2: KLayout DEF+LEF → GDS ────────────────────────────────────────────
echo "Step 2: KLayout GDS generation..."
mkdir -p "${CELLS_DIR}"
if command -v klayout &>/dev/null; then
    klayout -z -r gen_gds.py \
        -rd lef_file="${CELLS_DIR}/${CELL}.lef" \
        -rd def_file="${OUTPUT}/${DESIGN}.def" \
        -rd out_file="${CELLS_DIR}/${CELL}.gds" \
        2>&1 | tee output/klayout_gds.log
    echo "  ✓ GDS written: ${CELLS_DIR}/${CELL}.gds"
else
    echo "  ⚠ KLayout not found. EXTRA_GDS_FILES will be missing."
    echo "    Install: sudo apt install klayout"
    echo "    Or run inside Docker: docker run ... klayout -z -r gen_gds.py ..."
fi
echo ""

# ── Step 3: OpenROAD placement check ─────────────────────────────────────────
echo "Step 3: OpenROAD placement check..."
mkdir -p output/openroad
if command -v openroad &>/dev/null; then
    CELL_LEF="${CELLS_DIR}/${CELL}.lef" \
    DEF_FILE="${OUTPUT}/${DESIGN}.def" \
    OUT_DIR="output/openroad" \
    openroad -no_splash -exit openroad_flow.tcl \
        2>&1 | tee output/openroad_check.log
    echo "  ✓ Placement check passed — see output/openroad_check.log"
else
    echo "  ⚠ OpenROAD not found. Skipping placement check."
    echo "    Install: sudo apt install openroad"
fi
echo ""

# ── Step 4: LibreLane / OpenLane flow ────────────────────────────────────────
echo "Step 4: Full RTL-to-GDS flow..."

if command -v librelane &>/dev/null || python3 -m librelane --version &>/dev/null 2>&1; then
    echo "  Using LibreLane (successor to OpenLane)..."
    python3 -m librelane --config-file config.json 2>&1 | tee output/librelane.log
    echo "  ✓ LibreLane flow complete — see output/librelane.log"
elif [[ -n "${OPENLANE_ROOT}" ]] && [[ -f "${OPENLANE_ROOT}/flow.tcl" ]]; then
    echo "  Using OpenLane v1 (legacy, maintenance mode)..."
    echo "  Note: For new projects, use LibreLane (pip install librelane)"
    mkdir -p "${OPENLANE_ROOT}/designs/fecim_array/src"
    mkdir -p "${OPENLANE_ROOT}/designs/fecim_array/cells"
    cp "${OUTPUT}/${DESIGN}.v" "${OPENLANE_ROOT}/designs/fecim_array/src/"
    cp "config.json" "${OPENLANE_ROOT}/designs/fecim_array/"
    cp -r "${CELLS_DIR}" "${OPENLANE_ROOT}/designs/fecim_array/cells/" 2>/dev/null || true
    cd "${OPENLANE_ROOT}"
    ./flow.tcl -design fecim_array 2>&1 | tee "${OLDPWD}/output/openlane.log"
    echo "  ✓ OpenLane flow complete — see output/openlane.log"
else
    echo "  ⚠ Neither LibreLane nor OpenLane found."
    echo "    Install LibreLane: pip install librelane"
    echo "    Docs: https://librelane.readthedocs.io/"
    echo ""
    echo "    Or use Docker:"
    echo "    docker run --rm -v \$PWD:/design -w /design \\"
    echo "      ghcr.io/the-openroad-project/openlane:latest \\"
    echo "      python3 -m librelane --config-file /design/config.json"
fi

echo ""
echo "==================================================="
echo "Flow complete for ${DESIGN}"
echo "Outputs:"
echo "  Verilog: ${OUTPUT}/${DESIGN}.v"
echo "  DEF:     ${OUTPUT}/${DESIGN}.def"
echo "  GDS:     ${CELLS_DIR}/${CELL}.gds"
echo "  Config:  config.json"
echo "==================================================="
`, time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture,
		designName, cellName)
}

// GenerateLibreLaneConfig returns a LibreLane-compatible config.json.
// LibreLane (https://librelane.readthedocs.io) is the Python-based successor
// to OpenLane v1. It uses the same JSON config format with some extensions.
//
// Key differences from GenerateOpenLaneConfig:
//   - Correct version comment (v1/LibreLane, not "v2.0")
//   - BASE_SDC_FILE reference for timing constraints
//   - KLAYOUT_DRC_KLAYOUT_SCRIPT for DRC
//   - Explicit DESIGN_IS_CORE=false (macro, not full chip)
func GenerateLibreLaneConfig(cfg config.ArrayConfig) string {
	designName := fmt.Sprintf("fecim_crossbar_%dx%d", cfg.Rows, cfg.Cols)
	cellName := cellNameFromArch(cfg.Architecture)
	dieW := float64(cfg.Cols)*cfg.CellWidth + 2.0
	dieH := float64(cfg.Rows)*cfg.CellHeight + 2.0

	return fmt.Sprintf(`{
  "_comment": "FeCIM crossbar LibreLane / OpenLane v1 configuration",
  "_generated": "%s",
  "_tool_compat": "LibreLane (https://librelane.readthedocs.io) and OpenLane v1.x",
  "_note": "For new designs use LibreLane: pip install librelane",
  "_array": "%dx%d %s (%s)",

  "DESIGN_NAME": "%s",
  "DESIGN_IS_CORE": 0,

  "VERILOG_FILES": "dir::output/%s.v",
  "VERILOG_FILES_BLACKBOX": "dir::cells/%s/%s.v",

  "BASE_SDC_FILE": "dir::constraints.sdc",

  "RUN_CTS": 0,

  "FP_SIZING": "absolute",
  "DIE_AREA": "0 0 %.3f %.3f",

  "FP_DEF_TEMPLATE": "dir::output/%s.def",
  "PL_SKIP_INITIAL_PLACEMENT": 1,
  "PL_TARGET_DENSITY": 0.6,

  "EXTRA_LEFS": "dir::cells/%s/%s.lef",
  "EXTRA_LIBS": "dir::cells/%s/%s.lib",
  "EXTRA_GDS_FILES": "dir::cells/%s/%s.gds",

  "_gds_note": "GDS generated by: klayout -z -r gen_gds.py (see gen_gds.py in this directory)",

  "SYNTH_ELABORATE_ONLY": 1,
  "SYNTH_READ_BLACKBOX_LIB": 1,

  "KLAYOUT_DRC_KLAYOUT_SCRIPT": "",

  "_macros_note": "OpenLane 2 / LibreLane prefers MACROS dict over flat EXTRA_* for custom cells",
  "MACROS": {
    "%s": {
      "gds": ["dir::cells/%s/%s.gds"],
      "lef": ["dir::cells/%s/%s.lef"],
      "lib": {
        "*": ["dir::cells/%s/%s.lib"]
      },
      "nl": ["dir::cells/%s/%s.v"]
    }
  },

  "_flow_note": "Run flow: python3 -m librelane --config-file config.json"
}
`,
		time.Now().Format("2006-01-02"),
		cfg.Rows, cfg.Cols, cfg.Architecture, cfg.Technology,
		designName,
		designName, cellName, cellName,
		dieW, dieH,
		designName,
		cellName, cellName,
		cellName, cellName,
		cellName, cellName,
		// MACROS dict: cellName (key), gds, lef, lib, nl paths
		cellName,
		cellName, cellName,
		cellName, cellName,
		cellName, cellName,
		cellName, cellName)
}

// cellNameFromArch maps architecture to cell library name.
func cellNameFromArch(arch string) string {
	switch strings.ToLower(arch) {
	case "1t1r":
		return "fecim_1t1r_bitcell"
	case "2t1r":
		return "fecim_2t1r_bitcell"
	default:
		return "fecim_bitcell"
	}
}
