// pkg/export/spice.go
package export

import (
	"fmt"
	"os"
	"strings"

	"fecim-lattice-tools/module6-eda/pkg/compiler"
	sharedexport "fecim-lattice-tools/shared/export"
	"fecim-lattice-tools/shared/logging"
	sharedphysics "fecim-lattice-tools/shared/physics"
)

var logSPICE = logging.NewLogger("eda-export-spice")

// FeFETMaterial describes ferroelectric stack parameters used by SPICE generator.
type FeFETMaterial struct {
	RelativePermittivity float64 // εr
	ThicknessM           float64 // Ferroelectric thickness (m)
	AreaM2               float64 // Device area (m^2)
	CoerciveFieldVM      float64 // Ec (V/m)
}

// DefaultHzoFeFETMaterial returns default HZO values used by Module 6 SPICE export.
func DefaultHzoFeFETMaterial() FeFETMaterial {
	return FeFETMaterial{
		RelativePermittivity: 25.0,
		ThicknessM:           10e-9,
		AreaM2:               2.025e-15,
		CoerciveFieldVM:      1e8,
	}
}

func generateSky130NMOSModelCard() string {
	sel := sharedphysics.SKY130NMOS()
	return fmt.Sprintf(".model SKY130NMOS NMOS (LEVEL=1 VTO=%.6g KP=120e-6 LAMBDA=0.03)\n* SKY130 selector preset from shared/physics/selector.go: W=%.12e L=%.12e Ion=%.6e Ioff=%.6e Cgate=%.6e\n\n",
		sel.Vth, sel.W, sel.L, sel.Ion, sel.Ioff, sel.Cgate)
}

// GenerateFeFETSubcircuit creates the FeFET primitive using shared LK FeCap export.
func GenerateFeFETSubcircuit(mat FeFETMaterial) string {
	if mat.RelativePermittivity <= 0 {
		mat.RelativePermittivity = 25.0
	}
	if mat.ThicknessM <= 0 {
		mat.ThicknessM = 10e-9
	}
	if mat.AreaM2 <= 0 {
		mat.AreaM2 = 2.025e-15
	}

	params := sharedexport.DefaultMaterlikFECapParams()
	params.Name = "FECAP_HZO"
	params.EpsR = mat.RelativePermittivity
	params.Thick_m = mat.ThicknessM
	params.Area_m2 = mat.AreaM2

	var sb strings.Builder
	sb.WriteString(sharedexport.GenerateFECapSubcircuit(params))
	sb.WriteString("\n")
	sb.WriteString(".subckt fefet_cell TE BE PARAMS: R_level=1e4\n")
	sb.WriteString("* FeFET wrapper: programmable channel resistance + LK ferroelectric capacitor\n")
	sb.WriteString("Rfe TE n1 {R_level}\n")
	sb.WriteString("XFE n1 BE FECAP_HZO\n")
	sb.WriteString(".ends fefet_cell\n\n")
	return sb.String()
}

// Generate1T1RSubcircuit creates selector-transistor + FeFET (1T1R) bitcell.
func Generate1T1RSubcircuit() string {
	sel := sharedphysics.SKY130NMOS()
	var sb strings.Builder
	sb.WriteString(".subckt fefet_1t1r WL BL SL PARAMS: R_level=1e4\n")
	sb.WriteString("* 1T1R bitcell: SKY130 NMOS selector + FeFET\n")
	sb.WriteString(fmt.Sprintf("MSEL n1 WL SL SL SKY130NMOS W=%.12e L=%.12e\n", sel.W, sel.L))
	sb.WriteString("XFE n1 BL fefet_cell R_level={R_level}\n")
	sb.WriteString(".ends fefet_1t1r\n\n")
	return sb.String()
}

// Generate2T1RSubcircuit creates dual-selector-transistor + FeFET (2T1R) bitcell.
func Generate2T1RSubcircuit() string {
	sel := sharedphysics.SKY130NMOS()
	var sb strings.Builder
	sb.WriteString(".subckt fefet_2t1r WL CSL BL SL PARAMS: R_level=1e4\n")
	sb.WriteString("* 2T1R bitcell: row/column SKY130 NMOS selectors in series + FeFET\n")
	sb.WriteString(fmt.Sprintf("MROW n1 WL n2 n2 SKY130NMOS W=%.12e L=%.12e\n", sel.W, sel.L))
	sb.WriteString(fmt.Sprintf("MCOL n2 CSL SL SL SKY130NMOS W=%.12e L=%.12e\n", sel.W, sel.L))
	sb.WriteString("XFE n1 BL fefet_cell R_level={R_level}\n")
	sb.WriteString(".ends fefet_2t1r\n\n")
	return sb.String()
}

// GenerateSPICE creates ngspice-compatible netlist.
// Works with all operation modes (Storage, Memory, Compute).
func GenerateSPICE(design *compiler.ArrayDesign, vdd float64) string {
	logSPICE.Input("GenerateSPICE", map[string]interface{}{
		"mode":        design.Config.Mode,
		"totalCells":  design.Stats.TotalCells,
		"activeCells": design.Stats.ActiveCells,
		"vdd":         vdd,
	})

	var sb strings.Builder

	// Filter cells to export
	cellsToExport := filterActiveCells(design)

	sb.WriteString(characterizationProvenanceBlockSpice)
	sb.WriteString("* FeCIM Array SPICE Netlist\n")
	sb.WriteString("* Generated by Module 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("* Operation Mode: %s\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("* Array: %d cells\n\n", len(cellsToExport)))

	// Device subcircuits
	sb.WriteString(GenerateFeFETSubcircuit(DefaultHzoFeFETMaterial()))
	arch := strings.ToLower(design.Config.Architecture)
	if arch == compiler.Arch1T1R || arch == compiler.Arch2T1R {
		sb.WriteString(generateSky130NMOSModelCard())
	}
	if arch == compiler.Arch1T1R {
		sb.WriteString(Generate1T1RSubcircuit())
	}
	if arch == compiler.Arch2T1R {
		sb.WriteString(Generate2T1RSubcircuit())
	}

	// Architecture-specific pin model for cross-format checks
	spicePins := []string{"WL", "BL", "VPWR", "VGND"}
	if arch == compiler.Arch1T1R || arch == compiler.Arch2T1R {
		spicePins = append(spicePins, "SL")
	}
	if arch == compiler.Arch2T1R {
		spicePins = append(spicePins, "CSL")
	}
	sb.WriteString(fmt.Sprintf(".subckt fecim_cell %s\n", strings.Join(spicePins, " ")))
	sb.WriteString("* Placeholder FeCIM cell interface for cross-format validation\n")
	sb.WriteString(".ends fecim_cell\n\n")

	// Power supply
	sb.WriteString(fmt.Sprintf(".param VDD = %.2f\n", vdd))
	sb.WriteString("VDD vdd 0 DC {VDD}\n\n")

	// Find array dimensions from cells to export
	maxRow, maxCol := findCellDimensions(cellsToExport)

	// Word line drivers (inputs)
	sb.WriteString("* Word Line Drivers\n")
	for row := 0; row <= maxRow; row++ {
		sb.WriteString(fmt.Sprintf("VWL%d wl%d 0 DC 0\n", row, row))
	}
	sb.WriteString("\n")

	if arch == compiler.Arch1T1R || arch == compiler.Arch2T1R {
		// SL is per-column (like BL), not per-row — consistent with Verilog SL[numCols-1:0].
		sb.WriteString("* Source Line Drivers (per-column, one per BL)\n")
		for col := 0; col <= maxCol; col++ {
			sb.WriteString(fmt.Sprintf("VSL%d sl%d 0 DC 0\n", col, col))
		}
		sb.WriteString("\n")
	}
	if arch == compiler.Arch2T1R {
		sb.WriteString("* Column Select Line Drivers\n")
		for col := 0; col <= maxCol; col++ {
			sb.WriteString(fmt.Sprintf("VCSL%d csl%d 0 DC 0\n", col, col))
		}
		sb.WriteString("\n")
	}

	// Bit line loads
	sb.WriteString("* Bit Line Loads (1k for sensing)\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("RBL%d bl%d 0 1k\n", col, col))
	}
	sb.WriteString("\n")

	// FeFET cells as subcircuit instances
	sb.WriteString("* FeFET Cells (subcircuit model: R_level = 1/G + LK FeCap)\n")
	for _, cell := range cellsToExport {
		// Use Resistance field if set, otherwise calculate from Conductance
		resistance := cell.Resistance
		if resistance == 0 && cell.Conductance > 0 {
			resistance = 1e6 / cell.Conductance // Ω from μS
		}
		if resistance <= 0 {
			resistance = 1e9
		}

		if arch == compiler.Arch1T1R {
			// SL is per-column (consistent with Verilog .SL(SL[col])).
			sb.WriteString(fmt.Sprintf("X_%d_%d wl%d bl%d sl%d fefet_1t1r R_level=%.2f\n",
				cell.Row, cell.Col, cell.Row, cell.Col, cell.Col, resistance))
		} else if arch == compiler.Arch2T1R {
			// SL is per-column (consistent with Verilog .SL(SL[col])).
			sb.WriteString(fmt.Sprintf("X_%d_%d wl%d csl%d bl%d sl%d fefet_2t1r R_level=%.2f\n",
				cell.Row, cell.Col, cell.Row, cell.Col, cell.Col, cell.Col, resistance))
		} else {
			sb.WriteString(fmt.Sprintf("X_%d_%d wl%d bl%d fefet_cell R_level=%.2f LEVEL=%d\n",
				cell.Row, cell.Col, cell.Row, cell.Col, resistance, cell.Level))
		}
	}
	sb.WriteString("\n")

	// Analysis
	sb.WriteString("* Analysis\n")
	sb.WriteString(".op\n")
	sb.WriteString(".control\n")
	sb.WriteString("run\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("print i(RBL%d)\n", col))
	}
	sb.WriteString(".endc\n")
	sb.WriteString(".end\n")

	netlist := sb.String()

	logSPICE.Calculation("GenerateSPICE", map[string]interface{}{
		"cellsExported": len(cellsToExport),
		"wordLines":     maxRow + 1,
		"bitLines":      maxCol + 1,
		"netlistSize":   len(netlist),
	}, nil)

	return netlist
}

// ExportSPICE writes netlist to file.
// Works with all operation modes (Storage, Memory, Compute).
func ExportSPICE(design *compiler.ArrayDesign, path string, vdd float64) error {
	logSPICE.Input("ExportSPICE", map[string]interface{}{
		"path": path,
		"vdd":  vdd,
	})

	content := GenerateSPICE(design, vdd)

	err := os.WriteFile(path, []byte(content), 0644)
	if err != nil {
		logSPICE.ErrorContext("ExportSPICE", err, map[string]interface{}{
			"path": path,
		})
		return err
	}

	logSPICE.Debug("ExportSPICE: Exported netlist to %s (size: %d bytes)", path, len(content))

	return nil
}
