// pkg/export/spice.go
package export

import (
	"fmt"
	"os"
	"strings"

	"fecim-lattice-tools/module6-eda/pkg/compiler"
	"fecim-lattice-tools/shared/logging"
)

var logSPICE = logging.NewLogger("eda-export-spice")

const vacuumPermittivity = 8.854e-12 // F/m

// FeFETMaterial describes ferroelectric stack parameters used by SPICE generator.
type FeFETMaterial struct {
	RelativePermittivity float64 // εr
	ThicknessM           float64 // Ferroelectric thickness (m)
	AreaM2               float64 // Device area (m^2)
	CoerciveFieldVM      float64 // Ec (V/m)
}

// DefaultHzoFeFETMaterial returns default HZO values used by Module 6 SPICE export.
// Effective default area is chosen so C_fe is in the expected ~2.2fF range.
func DefaultHzoFeFETMaterial() FeFETMaterial {
	return FeFETMaterial{
		RelativePermittivity: 25.0,
		ThicknessM:           10e-9,
		AreaM2:               1e-13,
		CoerciveFieldVM:      1e8,
	}
}

// GenerateFeFETSubcircuit creates the FeFET primitive with ferroelectric capacitance.
func GenerateFeFETSubcircuit(mat FeFETMaterial) string {
	if mat.RelativePermittivity <= 0 {
		mat.RelativePermittivity = 25.0
	}
	if mat.ThicknessM <= 0 {
		mat.ThicknessM = 10e-9
	}
	if mat.AreaM2 <= 0 {
		mat.AreaM2 = 1e-13
	}
	if mat.CoerciveFieldVM <= 0 {
		mat.CoerciveFieldVM = 1e8
	}

	cFe := vacuumPermittivity * mat.RelativePermittivity * mat.AreaM2 / mat.ThicknessM
	vc := mat.CoerciveFieldVM * mat.ThicknessM

	var sb strings.Builder
	sb.WriteString(".subckt fefet_cell TE BE LEVEL=15\n")
	sb.WriteString("* Voltage-dependent FeFET: piecewise linear G(V)\n")
	sb.WriteString("* Below Vc: G = Gmin (HRS), Above Vc: G = Gmax (LRS)\n")
	sb.WriteString("* Vc = coercive voltage = Ec * thickness\n")
	sb.WriteString(fmt.Sprintf("* Computed defaults: C_fe=%.3ef F, Vc=%.3f V\n", cFe*1e15, vc))
	sb.WriteString(fmt.Sprintf(".param C_fe=%.6e\n", cFe))
	sb.WriteString(".param R_level=1e4\n")
	sb.WriteString("Rfe TE n1 {R_level}\n")
	sb.WriteString("Cfe n1 BE {C_fe}\n")
	sb.WriteString(".ends fefet_cell\n\n")
	return sb.String()
}

// Generate1T1RSubcircuit creates selector-transistor + FeFET (1T1R) bitcell.
func Generate1T1RSubcircuit() string {
	var sb strings.Builder
	sb.WriteString(".subckt fefet_1t1r WL BL SL R_level=1e4\n")
	sb.WriteString("* 1T1R bitcell: access NMOS + FeFET\n")
	sb.WriteString("MSEL n1 WL SL SL NMOS W=1u L=0.15u\n")
	sb.WriteString("XFE n1 BL fefet_cell R_level={R_level}\n")
	sb.WriteString(".ends fefet_1t1r\n\n")
	return sb.String()
}

// GenerateSPICE creates ngspice-compatible netlist.
// Works with all operation modes (Storage, Memory, Compute).
func GenerateSPICE(design *compiler.ArrayDesign, vdd float64) string {
	logSPICE.Input("GenerateSPICE", map[string]interface{}{
		"mode":        design.Config.Mode,
		"totalCells":  design.Stats.TotalCells,
		"activeCells": design.Stats.ActiveCells,
		"vdd":         vdd,
	})

	var sb strings.Builder

	// Filter cells to export
	cellsToExport := filterActiveCells(design)

	sb.WriteString("* FeCIM Array SPICE Netlist\n")
	sb.WriteString("* Generated by Module 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("* Operation Mode: %s\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("* Array: %d cells\n\n", len(cellsToExport)))

	// Device subcircuits
	sb.WriteString(GenerateFeFETSubcircuit(DefaultHzoFeFETMaterial()))
	if design.Config.Architecture == compiler.Arch1T1R {
		sb.WriteString(".model NMOS NMOS LEVEL=1\n\n")
		sb.WriteString(Generate1T1RSubcircuit())
	}

	// Architecture-specific pin model for cross-format checks
	arch := strings.ToLower(design.Config.Architecture)
	spicePins := []string{"WL", "BL", "VPWR", "VGND"}
	if arch == compiler.Arch1T1R || arch == compiler.Arch2T1R {
		spicePins = append(spicePins, "SL")
	}
	if arch == compiler.Arch2T1R {
		spicePins = append(spicePins, "CSL")
	}
	sb.WriteString(fmt.Sprintf(".subckt fecim_cell %s\n", strings.Join(spicePins, " ")))
	sb.WriteString("* Placeholder FeCIM cell interface for cross-format validation\n")
	sb.WriteString(".ends fecim_cell\n\n")

	// Power supply
	sb.WriteString(fmt.Sprintf(".param VDD = %.2f\n", vdd))
	sb.WriteString("VDD vdd 0 DC {VDD}\n\n")

	// Find array dimensions from cells to export
	maxRow, maxCol := findCellDimensions(cellsToExport)

	// Word line drivers (inputs)
	sb.WriteString("* Word Line Drivers\n")
	for row := 0; row <= maxRow; row++ {
		sb.WriteString(fmt.Sprintf("VWL%d wl%d 0 DC 0\n", row, row))
	}
	sb.WriteString("\n")

	// Source lines for 1T1R
	if design.Config.Architecture == compiler.Arch1T1R {
		sb.WriteString("* Source Line Bias\n")
		for row := 0; row <= maxRow; row++ {
			sb.WriteString(fmt.Sprintf("VSL%d sl%d 0 DC 0\n", row, row))
		}
		sb.WriteString("\n")
	}

	if arch == compiler.Arch1T1R || arch == compiler.Arch2T1R {
		sb.WriteString("* Source Line Drivers\n")
		for col := 0; col <= maxCol; col++ {
			sb.WriteString(fmt.Sprintf("VSL%d sl%d 0 DC 0\n", col, col))
		}
		sb.WriteString("\n")
	}
	if arch == compiler.Arch2T1R {
		sb.WriteString("* Column Select Line Drivers\n")
		for col := 0; col <= maxCol; col++ {
			sb.WriteString(fmt.Sprintf("VCSL%d csl%d 0 DC 0\n", col, col))
		}
		sb.WriteString("\n")
	}

	// Bit line loads
	sb.WriteString("* Bit Line Loads (1k for sensing)\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("RBL%d bl%d 0 1k\n", col, col))
	}
	sb.WriteString("\n")

	// FeFET cells as subcircuit instances
	sb.WriteString("* FeFET Cells (subcircuit model: R_level = 1/G, includes C_fe)\n")
	for _, cell := range cellsToExport {
		// Use Resistance field if set, otherwise calculate from Conductance
		resistance := cell.Resistance
		if resistance == 0 && cell.Conductance > 0 {
			resistance = 1e6 / cell.Conductance // Ω from μS
		}
		if resistance <= 0 {
			resistance = 1e9
		}

		if design.Config.Architecture == compiler.Arch1T1R {
			sb.WriteString(fmt.Sprintf("X_%d_%d wl%d bl%d sl%d fefet_1t1r R_level=%.2f\n",
				cell.Row, cell.Col, cell.Row, cell.Col, cell.Row, resistance))
		} else {
			sb.WriteString(fmt.Sprintf("X_%d_%d wl%d bl%d fefet_cell R_level=%.2f LEVEL=%d\n",
				cell.Row, cell.Col, cell.Row, cell.Col, resistance, cell.Level))
		}
	}
	sb.WriteString("\n")

	// Analysis
	sb.WriteString("* Analysis\n")
	sb.WriteString(".op\n")
	sb.WriteString(".control\n")
	sb.WriteString("run\n")
	for col := 0; col <= maxCol; col++ {
		sb.WriteString(fmt.Sprintf("print i(RBL%d)\n", col))
	}
	sb.WriteString(".endc\n")
	sb.WriteString(".end\n")

	netlist := sb.String()

	logSPICE.Calculation("GenerateSPICE", map[string]interface{}{
		"cellsExported": len(cellsToExport),
		"wordLines":     maxRow + 1,
		"bitLines":      maxCol + 1,
		"netlistSize":   len(netlist),
	}, nil)

	return netlist
}

// ExportSPICE writes netlist to file.
// Works with all operation modes (Storage, Memory, Compute).
func ExportSPICE(design *compiler.ArrayDesign, path string, vdd float64) error {
	logSPICE.Input("ExportSPICE", map[string]interface{}{
		"path": path,
		"vdd":  vdd,
	})

	content := GenerateSPICE(design, vdd)

	err := os.WriteFile(path, []byte(content), 0644)
	if err != nil {
		logSPICE.ErrorContext("ExportSPICE", err, map[string]interface{}{
			"path": path,
		})
		return err
	}

	logSPICE.Debug("ExportSPICE: Exported netlist to %s (size: %d bytes)", path, len(content))

	return nil
}
