// pkg/export/verilog.go
// Verilog netlist generator for FeCIM crossbar arrays
// Supports both passive and 1T1R architectures

package export

import (
	"fmt"
	"os"
	"strings"
	"time"

	"multilayer-ferroelectric-cim-visualizer/module6-eda/pkg/compiler"
)

// VerilogConfig holds configuration for Verilog generation
type VerilogConfig struct {
	ModuleName string // Module name (default: fecim_crossbar)
	CellName   string // Cell instance type (default: fecim_bit)
}

// DefaultVerilogConfig returns standard Verilog generation parameters
func DefaultVerilogConfig() VerilogConfig {
	return VerilogConfig{
		ModuleName: "fecim_crossbar",
		CellName:   "fecim_bit",
	}
}

// GenerateVerilog creates Verilog netlist from ArrayDesign.
// Works with all operation modes (Storage, Memory, Compute).
// Architecture is determined from design.Config.Architecture:
//   - "passive": WL[], BL[] ports (sneak path susceptible)
//   - "1T1R": WL[], BL[], SL[] ports (sneak path mitigated)
// For compute mode with weights, only exports cells within weight matrix bounds.
// For other modes, exports all cells in the physical array.
func GenerateVerilog(design *compiler.ArrayDesign, config VerilogConfig) string {
	var sb strings.Builder

	// Filter cells to export based on mode
	cellsToExport := filterActiveCells(design)

	// Find array dimensions from cells to export
	maxRow, maxCol := findCellDimensions(cellsToExport)
	numRows := maxRow + 1
	numCols := maxCol + 1

	// Determine architecture
	arch := design.Config.Architecture
	if arch == "" {
		arch = compiler.ArchPassive // Default to passive if not specified
	}
	is1T1R := arch == compiler.Arch1T1R

	// Determine cell name based on architecture
	cellName := config.CellName
	if is1T1R && cellName == "fecim_bit" {
		cellName = "fecim_1t1r" // Use 1T1R-specific cell
	}

	// Check if this is compute mode with weights
	hasWeights := design.Config.Mode == compiler.ModeCompute &&
		design.Config.ComputeConfig != nil &&
		design.Config.ComputeConfig.InitialWeights != nil

	// Header comments
	sb.WriteString("// FeCIM Array Verilog Netlist\n")
	sb.WriteString("// Generated by Module 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("// Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("// Operation Mode: %s\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("// Array Size: %d rows x %d cols (%d cells)\n", numRows, numCols, len(cellsToExport)))
	sb.WriteString(fmt.Sprintf("// Architecture: %s\n", arch))
	sb.WriteString(fmt.Sprintf("// Technology: %s\n", design.Config.Technology))
	sb.WriteString(fmt.Sprintf("// Conductance Levels: %d\n", design.Config.Levels))
	if hasWeights {
		sb.WriteString("// Initial Weights: Pre-programmed from neural network\n")
	} else {
		sb.WriteString("// Initial State: Unprogrammed (will be configured during operation)\n")
	}
	if is1T1R {
		sb.WriteString("// Note: 1T1R architecture includes Source Lines (SL) for sneak path mitigation\n")
	}
	sb.WriteString("\n")

	// Module declaration with ports
	sb.WriteString(fmt.Sprintf("module %s (\n", config.ModuleName))
	sb.WriteString(fmt.Sprintf("    input  wire [%d:0] WL,  // Word Lines (row select)\n", numRows-1))
	sb.WriteString(fmt.Sprintf("    inout  wire [%d:0] BL,  // Bit Lines (column data)\n", numCols-1))
	if is1T1R {
		sb.WriteString(fmt.Sprintf("    input  wire [%d:0] SL,  // Source Lines (1T1R: transistor source)\n", numCols-1))
	}
	sb.WriteString("    input  wire       VDD, // Power supply\n")
	sb.WriteString("    input  wire       VSS  // Ground\n")
	sb.WriteString(");\n\n")

	// Parameters for documentation
	sb.WriteString("    // Array parameters\n")
	sb.WriteString(fmt.Sprintf("    parameter ROWS = %d;\n", numRows))
	sb.WriteString(fmt.Sprintf("    parameter COLS = %d;\n", numCols))
	sb.WriteString(fmt.Sprintf("    parameter LEVELS = %d;\n", design.Config.Levels))
	sb.WriteString(fmt.Sprintf("    parameter MODE = \"%s\";\n", design.Config.Mode))
	sb.WriteString(fmt.Sprintf("    parameter ARCHITECTURE = \"%s\";\n", arch))
	sb.WriteString("\n")

	// Cell instantiations
	sb.WriteString("    // FeCIM cell instances\n")
	sb.WriteString("    // Naming convention: R_{row}_{col}\n")
	sb.WriteString("    // Instance parameter: conductance level (0 to LEVELS-1)\n\n")

	for _, cell := range cellsToExport {
		// Instance name matches spice.go convention: R_{row}_{col}
		instanceName := fmt.Sprintf("R_%d_%d", cell.Row, cell.Col)

		// Comment format depends on whether weights are present
		if hasWeights && cell.InitialWeight != 0 {
			sb.WriteString(fmt.Sprintf("    // Cell [%d,%d]: weight=%.4f, level=%d, G=%.2f uS\n",
				cell.Row, cell.Col, cell.InitialWeight, cell.Level, cell.Conductance))
		} else {
			sb.WriteString(fmt.Sprintf("    // Cell [%d,%d]: level=%d, G=%.2f uS\n",
				cell.Row, cell.Col, cell.Level, cell.Conductance))
		}
		sb.WriteString(fmt.Sprintf("    %s #(.LEVEL(%d)) %s (\n",
			cellName, cell.Level, instanceName))
		sb.WriteString(fmt.Sprintf("        .WL  (WL[%d]),\n", cell.Row))
		sb.WriteString(fmt.Sprintf("        .BL  (BL[%d]),\n", cell.Col))
		if is1T1R {
			sb.WriteString(fmt.Sprintf("        .SL  (SL[%d]),\n", cell.Col))
		}
		sb.WriteString("        .VDD (VDD),\n")
		sb.WriteString("        .VSS (VSS)\n")
		sb.WriteString("    );\n\n")
	}

	sb.WriteString("endmodule\n")

	return sb.String()
}

// GenerateVerilogWithDefaults uses default configuration
func GenerateVerilogWithDefaults(design *compiler.ArrayDesign) string {
	return GenerateVerilog(design, DefaultVerilogConfig())
}

// ExportVerilog writes Verilog netlist to file
func ExportVerilog(design *compiler.ArrayDesign, path string) error {
	content := GenerateVerilogWithDefaults(design)
	return os.WriteFile(path, []byte(content), 0644)
}

// ExportVerilogWithConfig writes Verilog netlist to file with custom config
func ExportVerilogWithConfig(design *compiler.ArrayDesign, path string, config VerilogConfig) error {
	content := GenerateVerilog(design, config)
	return os.WriteFile(path, []byte(content), 0644)
}

// findArrayDimensions returns max row and col indices from design cells
// (kept for backward compatibility with def.go)
func findArrayDimensions(design *compiler.ArrayDesign) (maxRow, maxCol int) {
	return findCellDimensions(design.Cells)
}

// findCellDimensions returns max row and col indices from a cell slice
func findCellDimensions(cells []compiler.CellAssignment) (maxRow, maxCol int) {
	for _, cell := range cells {
		if cell.Row > maxRow {
			maxRow = cell.Row
		}
		if cell.Col > maxCol {
			maxCol = cell.Col
		}
	}
	return
}

// filterActiveCells returns cells that should be exported to Verilog.
// For compute mode with weights, returns only cells within weight matrix bounds.
// For other modes, returns all cells.
func filterActiveCells(design *compiler.ArrayDesign) []compiler.CellAssignment {
	// Check if this is compute mode with weights
	hasWeights := design.Config.Mode == compiler.ModeCompute &&
		design.Config.ComputeConfig != nil &&
		design.Config.ComputeConfig.InitialWeights != nil

	if !hasWeights {
		// Return all cells for non-compute modes
		return design.Cells
	}

	// For compute mode, find the dimensions of the weight matrix
	weights := design.Config.ComputeConfig.InitialWeights
	weightRows := len(weights)
	weightCols := 0
	if weightRows > 0 {
		weightCols = len(weights[0])
	}

	// Filter cells to only those within weight matrix bounds
	var activeCells []compiler.CellAssignment
	for _, cell := range design.Cells {
		if cell.Row < weightRows && cell.Col < weightCols {
			activeCells = append(activeCells, cell)
		}
	}

	return activeCells
}
