// pkg/export/verilog.go
// Verilog netlist generator for FeCIM crossbar arrays
// Supports both passive and 1T1R architectures

package export

import (
	"fmt"
	"os"
	"strings"
	"time"

	"multilayer-ferroelectric-cim-visualizer/module6-eda/pkg/compiler"
)

// VerilogConfig holds configuration for Verilog generation
type VerilogConfig struct {
	ModuleName string // Module name (default: fecim_crossbar)
	CellName   string // Cell instance type (default: fecim_bit)
}

// DefaultVerilogConfig returns standard Verilog generation parameters
func DefaultVerilogConfig() VerilogConfig {
	return VerilogConfig{
		ModuleName: "fecim_crossbar",
		CellName:   "fecim_bit",
	}
}

// GenerateVerilog creates Verilog netlist from CrossbarMapping
// Architecture is determined from mapping.Config.Architecture:
//   - "passive": WL[], BL[] ports (sneak path susceptible)
//   - "1T1R": WL[], BL[], SL[] ports (sneak path mitigated)
func GenerateVerilog(mapping *compiler.CrossbarMapping, config VerilogConfig) string {
	var sb strings.Builder

	// Find array dimensions from cell assignments
	maxRow, maxCol := findArrayDimensions(mapping)
	numRows := maxRow + 1
	numCols := maxCol + 1

	// Determine architecture
	arch := mapping.Config.Architecture
	if arch == "" {
		arch = compiler.ArchPassive // Default to passive if not specified
	}
	is1T1R := arch == compiler.Arch1T1R

	// Determine cell name based on architecture
	cellName := config.CellName
	if is1T1R && cellName == "fecim_bit" {
		cellName = "fecim_1t1r" // Use 1T1R-specific cell
	}

	// Header comments
	sb.WriteString("// FeCIM Crossbar Verilog Netlist\n")
	sb.WriteString("// Generated by Demo 6: FeCIM Design Suite\n")
	sb.WriteString(fmt.Sprintf("// Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("// Array Size: %d rows x %d cols (%d cells)\n", numRows, numCols, len(mapping.Cells)))
	sb.WriteString(fmt.Sprintf("// Architecture: %s\n", arch))
	sb.WriteString(fmt.Sprintf("// Quantization Levels: %d\n", mapping.Config.Levels))
	if is1T1R {
		sb.WriteString("// Note: 1T1R architecture includes Source Lines (SL) for sneak path mitigation\n")
	}
	sb.WriteString("\n")

	// Module declaration with ports
	sb.WriteString(fmt.Sprintf("module %s (\n", config.ModuleName))
	sb.WriteString(fmt.Sprintf("    input  wire [%d:0] WL,  // Word Lines (row select)\n", numRows-1))
	sb.WriteString(fmt.Sprintf("    inout  wire [%d:0] BL,  // Bit Lines (column data)\n", numCols-1))
	if is1T1R {
		sb.WriteString(fmt.Sprintf("    input  wire [%d:0] SL,  // Source Lines (1T1R: transistor source)\n", numCols-1))
	}
	sb.WriteString("    input  wire       VDD, // Power supply\n")
	sb.WriteString("    input  wire       VSS  // Ground\n")
	sb.WriteString(");\n\n")

	// Parameters for documentation
	sb.WriteString("    // Array parameters\n")
	sb.WriteString(fmt.Sprintf("    parameter ROWS = %d;\n", numRows))
	sb.WriteString(fmt.Sprintf("    parameter COLS = %d;\n", numCols))
	sb.WriteString(fmt.Sprintf("    parameter LEVELS = %d;\n", mapping.Config.Levels))
	sb.WriteString(fmt.Sprintf("    parameter ARCHITECTURE = \"%s\";\n", arch))
	sb.WriteString("\n")

	// Cell instantiations
	sb.WriteString("    // FeCIM cell instances\n")
	sb.WriteString("    // Naming convention: R_{row}_{col}\n")
	sb.WriteString("    // Instance parameter: quantization level (0 to LEVELS-1)\n\n")

	for _, cell := range mapping.Cells {
		// Instance name matches spice.go convention: R_{row}_{col}
		instanceName := fmt.Sprintf("R_%d_%d", cell.Row, cell.Col)

		sb.WriteString(fmt.Sprintf("    // Cell [%d,%d]: weight=%.4f, level=%d, G=%.2f uS\n",
			cell.Row, cell.Col, cell.WeightValue, cell.QuantLevel, cell.Conductance))
		sb.WriteString(fmt.Sprintf("    %s #(.LEVEL(%d)) %s (\n",
			cellName, cell.QuantLevel, instanceName))
		sb.WriteString(fmt.Sprintf("        .WL  (WL[%d]),\n", cell.Row))
		sb.WriteString(fmt.Sprintf("        .BL  (BL[%d]),\n", cell.Col))
		if is1T1R {
			sb.WriteString(fmt.Sprintf("        .SL  (SL[%d]),\n", cell.Col))
		}
		sb.WriteString("        .VDD (VDD),\n")
		sb.WriteString("        .VSS (VSS)\n")
		sb.WriteString("    );\n\n")
	}

	sb.WriteString("endmodule\n")

	return sb.String()
}

// GenerateVerilogWithDefaults uses default configuration
func GenerateVerilogWithDefaults(mapping *compiler.CrossbarMapping) string {
	return GenerateVerilog(mapping, DefaultVerilogConfig())
}

// ExportVerilog writes Verilog netlist to file
func ExportVerilog(mapping *compiler.CrossbarMapping, path string) error {
	content := GenerateVerilogWithDefaults(mapping)
	return os.WriteFile(path, []byte(content), 0644)
}

// ExportVerilogWithConfig writes Verilog netlist to file with custom config
func ExportVerilogWithConfig(mapping *compiler.CrossbarMapping, path string, config VerilogConfig) error {
	content := GenerateVerilog(mapping, config)
	return os.WriteFile(path, []byte(content), 0644)
}

// findArrayDimensions returns max row and col indices from cell assignments
func findArrayDimensions(mapping *compiler.CrossbarMapping) (maxRow, maxCol int) {
	for _, cell := range mapping.Cells {
		if cell.Row > maxRow {
			maxRow = cell.Row
		}
		if cell.Col > maxCol {
			maxCol = cell.Col
		}
	}
	return
}
